server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql:///lzy_blog
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: defFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: daddasd
  secretKey: weqeqwe
  bucket: uestclzy-blog

logging:
  config: /JAVA_programms/myblog_bili/myblog_blog/src/main/resources/logback-spring.xml


